Basic Autoclicker
AndersonUniversity/rodney-clicker pull request #11
Opened 2022-10-17 14:22 UTC by Mrcarroll66

2022-10-31 13:18 UTC, jgalford submitted a review, later dismissed
1. Number of clickers don't save after closing app.
2. Number of clickers get reset to 0 every time you open the store page.

2022-11-02 13:06 UTC, jgalford approved these changes

2022-11-04 14:36 UTC, Steadier requested changes
it failed the tests

2022-11-06 22:54 UTC, jgalford approved these changes

2022-11-07 02:49 UTC, jdspires00 approved these changes

2022-11-07 02:50 UTC, merged