change file names to rodneyClicker
AndersonUniversity/rodney-clicker pull request #17
Opened 2022-10-21 15:30 UTC by Steadier

2022-10-21 15:55 UTC, jgalford requested changes
Can you delete ExampleInstrumentedTest.kt and activity_display_message.xml? Otherwise I think it is good.

2022-10-24 14:08 UTC, Steadier commented
> Can you delete ExampleInstrumentedTest.kt and activity_display_message.xml? Otherwise I think it is good.

for sure

2022-10-24 14:20 UTC, jgalford approved these changes

2022-10-24 14:21 UTC, Mrcarroll66 approved these changes

2022-10-24 14:21 UTC, merged